### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by Dr-Terrible** [aeonurutu/shade#76]
When following the installation instructions from README.md, I got errors about missing packages from `go get github.com/aeonurutu/shade/...`:

> package github.com/aeonurutu/shade/entity: cannot find package "github.com/aeonurutu/shade/entity" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/entity (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/entity (from $GOPATH)
package github.com/aeonurutu/shade/fonts: cannot find package "github.com/aeonurutu/shade/fonts" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/fonts (from $GOROOT)
	/home/anonymous/my-projects/redpanda/shade-engine/src/github.com/aeonurutu/shade/fonts (from $GOPATH)
package github.com/aeonurutu/shade/shapes: cannot find package "github.com/aeonurutu/shade/shapes" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/shapes (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/shapes (from $GOPATH)
package github.com/aeonurutu/shade/sprite: cannot find package "github.com/aeonurutu/shade/sprite" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/sprite (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/sprite (from $GOPATH)

I'm not sure how to fix the issue since apparently `go generate github.com/aeonurutu/shade/...` does nothing. Neither `scripts/gen.sh` generates those missing files.

**Comment by hurricanerix** [comment]
Hi, thanks for the feedback.  I am in the process of re-writing/designing a lot of things.  So everything is kinda in a broken state.  I honestly didn't expect to have anybody find the project yet.  I have a goal of getting things stable and working by the end of the year.

If you don't mind providing some feedback on what you would like to use Shade for, it would be helpful to know as it progresses.

Thanks!

**Comment by Dr-Terrible** [comment]
>  I honestly didn't expect to have anybody find the project yet. 

Well, it showed up in github's search when I was looking for a game engine written in golang. There aren't a lot, and most of them are unfinished, or dead projects. `Shade` was one of the few with an active development, that is way I picked it up.

> If you don't mind providing some feedback on what you would like to use Shade for, it would be helpful to know as it progresses.

I'd like to use `shade` for rapid prototyping and building simple 2.5D games for game jam events like Ludum Dare and a-like, nothing else. Normally, I use SFML/GLFW/SDL for these kind of tasks, but since I'm a seasoned Golang developer I would like to ditch C++ in favour of Go.

I don't mind if `share` doesn't have a stable API; eventually, I can vendor a specific snapshot that fits my needs, provided that I can _go get_ it in the first place ;)

**Comment by hurricanerix** [comment]
> I'd like to use shade for rapid prototyping and building simple 2.5D games for game jam events like Ludum Dare and a-like

This is basically my overall goal, to have something that is very simple and fun to use for similar contests/projects/things.

If you don't mind, I would love to have a conversation directly with you about this.  Would you mind emailing me at hurricanerix@gmail.com?

**Comment by hurricanerix** [comment]
@Dr-Terrible Can you verify that this patch fixes your import issues?  (examples and demos are still kinda broken, but that should at least fix the import issue you were having)

**Comment by Dr-Terrible** [comment]
Unfortunately no. When running `go get github.com/hurricanerix/shade/...` (note that I'm not pulling from this repository but from your fork) in my GOPATH, I got a lot of new errors:

> package github.com/aeonurutu/shade/dev: cannot find package "github.com/aeonurutu/shade/dev" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/dev (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/dev (from $GOPATH)
package github.com/aeonurutu/shade/display: cannot find package "github.com/aeonurutu/shade/display" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/display (from $GOROOT)
	/home/eanonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/display (from $GOPATH)
package github.com/aeonurutu/shade/entity: cannot find package "github.com/aeonurutu/shade/entity" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/entity (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/entity (from $GOPATH)
package github.com/aeonurutu/shade/archive: cannot find package "github.com/aeonurutu/shade/archive" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/archive (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/archive (from $GOPATH)
package github.com/aeonurutu/shade/shader: cannot find package "github.com/aeonurutu/shade/shader" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/shader (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/shader (from $GOPATH)
package github.com/aeonurutu/shade/events: cannot find package "github.com/aeonurutu/shade/events" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/events (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/events (from $GOPATH)
package github.com/aeonurutu/shade/shapes: cannot find package "github.com/aeonurutu/shade/shapes" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/shapes (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/shapes (from $GOPATH)
package github.com/aeonurutu/shade/camera: cannot find package "github.com/aeonurutu/shade/camera" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/camera (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/camera (from $GOPATH)
package github.com/aeonurutu/shade/scene: cannot find package "github.com/aeonurutu/shade/scene" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/scene (from $GOROOT)
	/home/anonymous/my-projectsshade-engine/src/github.com/aeonurutu/shade/scene (from $GOPATH)
package github.com/aeonurutu/shade/sprite: cannot find package "github.com/aeonurutu/shade/sprite" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/sprite (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/sprite (from $GOPATH)
package github.com/aeonurutu/shade/time/clock: cannot find package "github.com/aeonurutu/shade/time/clock" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/time/clock (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/time/clock (from $GOPATH)
package github.com/aeonurutu/shade/fonts: cannot find package "github.com/aeonurutu/shade/fonts" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/fonts (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/fonts (from $GOPATH)
package github.com/aeonurutu/shade/light: cannot find package "github.com/aeonurutu/shade/light" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/light (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/light (from $GOPATH)
package github.com/aeonurutu/shade/examples/ex2-platform/game: cannot find package "github.com/aeonurutu/shade/examples/ex2-platform/game" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/examples/ex2-platform/game (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/examples/ex2-platform/game (from $GOPATH)
package github.com/aeonurutu/shade/splash: cannot find package "github.com/aeonurutu/shade/splash" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/splash (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/splash (from $GOPATH)
package github.com/aeonurutu/shade/examples/ex2-platform/block: cannot find package "github.com/aeonurutu/shade/examples/ex2-platform/block" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/examples/ex2-platform/block (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/examples/ex2-platform/block (from $GOPATH)
package github.com/aeonurutu/shade/examples/ex2-platform/player: cannot find package "github.com/aeonurutu/shade/examples/ex2-platform/player" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/examples/ex2-platform/player (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/examples/ex2-platform/player (from $GOPATH)
package github.com/aeonurutu/shade/examples/ex1-pong/game: cannot find package "github.com/aeonurutu/shade/examples/ex1-pong/game" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/examples/ex1-pong/game (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/examples/ex1-pong/game (from $GOPATH)
package github.com/aeonurutu/shade/examples/ex1-pong/player: cannot find package "github.com/aeonurutu/shade/examples/ex1-pong/player" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/examples/ex1-pong/player (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/examples/ex1-pong/player (from $GOPATH)
package github.com/aeonurutu/shade/examples/ex1-pong/ball: cannot find package "github.com/aeonurutu/shade/examples/ex1-pong/ball" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/examples/ex1-pong/ball (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/examples/ex1-pong/ball (from $GOPATH)
package github.com/aeonurutu/shade/splash/ghost: cannot find package "github.com/aeonurutu/shade/splash/ghost" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/splash/ghost (from $GOROOT)
	/home/anonymous/my-projects/shade-engine/src/github.com/aeonurutu/shade/splash/ghost

**Comment by Dr-Terrible** [comment]
Just in case, my setup is quite easy to replicate:

```sh
$ mkdir ~/shade-engine/
$ cd ~/shade-engine/
$ export GOPATH="$PWD"
$ export GOBIN="$PWD/bin"
$ go env
GOARCH="amd64"
GOBIN="/home/anonymous/shade-engine/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/anonymous/shade-engine"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
```

Then I go get Shade:
```shell
$ go get -v -u github.com/aeonurutu/shade/...
github.com/hurricanerix/shade (download)
github.com/aeonurutu/shade (download)
package github.com/hurricanerix/shade
	imports github.com/aeonurutu/shade/dev: cannot find package "github.com/aeonurutu/shade/dev" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/dev (from $GOROOT)
	/home/anonymous/shade-engine/src/github.com/aeonurutu/shade/dev (from $GOPATH)
package github.com/hurricanerix/shade
	imports github.com/aeonurutu/shade/display: cannot find package "github.com/aeonurutu/shade/display" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/display (from $GOROOT)
	/home/anonymous/shade-engine/src/github.com/aeonurutu/shade/display (from $GOPATH)
package github.com/hurricanerix/shade
	imports github.com/aeonurutu/shade/entity: cannot find package "github.com/aeonurutu/shade/entity" in any of:
	/usr/lib/go/src/github.com/aeonurutu/shade/entity (from $GOROOT)
	/home/anonymous/shade-engine/src/github.com/aeonurutu/shade/entity (from $GOPATH)
[...]

$ tree . -d 
.
└── src
    ├── github.com
    │   ├── aeonurutu
    │   │   └── shade
    │   │       ├── assets
    │   │       │   └── shaders
    │   │       ├── core
    │   │       │   ├── camera
    │   │       │   ├── dev
    │   │       │   ├── display
    │   │       │   ├── entity
    │   │       │   ├── events
    │   │       │   ├── gen
    │   │       │   ├── light
    │   │       │   ├── scene
    │   │       │   ├── shader
    │   │       │   ├── shapes
    │   │       │   ├── splash
    │   │       │   │   └── ghost
    │   │       │   ├── time
    │   │       │   │   └── clock
    │   │       │   └── util
    │   │       │       ├── actor
    │   │       │       ├── archive
    │   │       │       ├── fonts
    │   │       │       └── sprite
    │   │       ├── examples
    │   │       │   ├── 01-basic
    │   │       │   ├── 02-animation
    │   │       │   ├── 03-basic-collisions
    │   │       │   │   ├── ball
    │   │       │   │   ├── block
    │   │       │   │   └── player
    │   │       │   ├── 03-collisions
    │   │       │   │   ├── ball
    │   │       │   │   └── block
    │   │       │   ├── 04-lighting
    │   │       │   ├── 05-text
    │   │       │   ├── assets
    │   │       │   └── demos
    │   │       │       ├── platformer
    │   │       │       │   ├── block
    │   │       │       │   ├── game
    │   │       │       │   └── player
    │   │       │       └── pong
    │   │       │           ├── ball
    │   │       │           ├── game
    │   │       │           └── player
    │   │       ├── gen
    │   │       └── scripts
    │   ├── go-gl
    │   │   ├── gl
    │   │   │   ├── all-core
    │   │   │   │   └── gl
    │   │   │   ├── v2.1
    │   │   │   │   └── gl
    │   │   │   ├── v3.1
    │   │   │   │   └── gles2
    │   │   │   ├── v3.2-compatibility
    │   │   │   │   └── gl
    │   │   │   ├── v3.2-core
    │   │   │   │   └── gl
    │   │   │   ├── v3.3-compatibility
    │   │   │   │   └── gl
    │   │   │   ├── v3.3-core
    │   │   │   │   └── gl
    │   │   │   ├── v4.1-compatibility
    │   │   │   │   └── gl
    │   │   │   ├── v4.1-core
    │   │   │   │   └── gl
    │   │   │   ├── v4.4-compatibility
    │   │   │   │   └── gl
    │   │   │   ├── v4.4-core
    │   │   │   │   └── gl
    │   │   │   ├── v4.5-compatibility
    │   │   │   │   └── gl
    │   │   │   └── v4.5-core
    │   │   │       └── gl
    │   │   ├── glfw
    │   │   │   ├── v3.0
    │   │   │   │   └── glfw
    │   │   │   ├── v3.1
    │   │   │   │   └── glfw
    │   │   │   │       └── glfw
    │   │   │   │           ├── deps
    │   │   │   │           │   ├── EGL
    │   │   │   │           │   ├── GL
    │   │   │   │           │   ├── glad
    │   │   │   │           │   └── KHR
    │   │   │   │           ├── include
    │   │   │   │           │   └── GLFW
    │   │   │   │           └── src
    │   │   │   └── v3.2
    │   │   │       └── glfw
    │   │   │           └── glfw
    │   │   │               ├── deps
    │   │   │               │   ├── glad
    │   │   │               │   ├── KHR
    │   │   │               │   ├── mingw
    │   │   │               │   └── vulkan
    │   │   │               ├── include
    │   │   │               │   └── GLFW
    │   │   │               └── src
    │   │   └── mathgl
    │   │       ├── mgl32
    │   │       │   └── matstack
    │   │       └── mgl64
    │   │           └── matstack
    │   └── hurricanerix
    │       └── shade
    │           ├── actor
    │           ├── archive
    │           ├── assets
    │           │   └── shaders
    │           ├── camera
    │           ├── dev
    │           ├── display
    │           ├── entity
    │           ├── events
    │           ├── examples
    │           │   ├── 01-basic
    │           │   ├── 02-animation
    │           │   ├── 03-basic-collisions
    │           │   │   ├── ball
    │           │   │   ├── block
    │           │   │   └── player
    │           │   ├── 03-collisions
    │           │   │   ├── ball
    │           │   │   └── block
    │           │   ├── 04-lighting
    │           │   ├── 05-text
    │           │   ├── assets
    │           │   └── demos
    │           │       ├── platformer
    │           │       │   ├── block
    │           │       │   ├── game
    │           │       │   └── player
    │           │       └── pong
    │           │           ├── ball
    │           │           ├── game
    │           │           └── player
    │           ├── fonts
    │           ├── gen
    │           ├── light
    │           ├── scene
    │           ├── shader
    │           ├── shapes
    │           ├── splash
    │           │   └── ghost
    │           ├── sprite
    │           └── time
    │               └── clock
    └── golang.org
        └── x
            └── image
                ├── bmp
                ├── cmd
                │   └── webp-manual-test
                ├── colornames
                ├── draw
                ├── example
                │   └── font
                ├── font
                │   ├── basicfont
                │   ├── inconsolata
                │   ├── plan9font
                │   └── testdata
                │       └── fixed
                ├── math
                │   ├── f32
                │   ├── f64
                │   └── fixed
                ├── riff
                ├── testdata
                ├── tiff
                │   └── lzw
                ├── vp8
                ├── vp8l
                └── webp
                    └── nycbcra
``` 
Obviously, the fork `github.com/hurricanerix/shade` is importing `github.com/aeonurutu/shade` (which doesn't have the new fixes), thus confusing the Golang compiler; you cannot cross-importing packages, see https://golang.org/doc/code.html.

**Comment by hurricanerix** [comment]
Yeah, go imports occasionally burns me by grabbing the wrong things.  I thought it was all fixed, but I guess I missed some again...

I'll try to go through this tonight (replicating your setup) and fix it.

**Comment by hurricanerix** [comment]
@Dr-Terrible Putting some comments inline

This part is similar to yours

```shell
$ mkdir /tmp/shade-engine
$ cd /tmp/shade-engine
$ export GOPATH="$PWD"
$ export GOBIN="$PWD/bin"
$ go env
GOARCH="amd64"
GOBIN="/tmp/shade-engine/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/tmp/shade-engine"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

However, here instead of issuing a "$ go get -v -u github.com/aeonurutu/shade/..." I am pulling the branch with my fixed imports manually.

```shell
$ mkdir -p src/github.com/aeonurutu
$ cd src/github.com/aeonurutu
$ git clone git@github.com:hurricanerix/shade.git
Cloning into 'shade'...
remote: Counting objects: 2232, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2232 (delta 2), reused 0 (delta 0), pack-reused 2219
Receiving objects: 100% (2232/2232), 3.06 MiB | 1.43 MiB/s, done.
Resolving deltas: 100% (1157/1157), done.
Checking connectivity... done.
$ cd shade
$ git checkout imports
Branch imports set up to track remote branch imports from origin.
Switched to a new branch 'imports'
```

Now I am successfully (I think) installing them from the cloned directory.

```shell
$ go get -v -u ./...
github.com/aeonurutu/shade (download)
github.com/go-gl/gl (download)
github.com/go-gl/glfw (download)
github.com/go-gl/mathgl (download)
Fetching https://golang.org/x/image/math/f32?go-get=1
Parsing meta tags from https://golang.org/x/image/math/f32?go-get=1 (status code 200)
get "golang.org/x/image/math/f32": found meta tag main.metaImport{Prefix:"golang.org/x/image", VCS:"git", RepoRoot:"https://go.googlesource.com/image"} at https://golang.org/x/image/math/f32?go-get=1
get "golang.org/x/image/math/f32": verifying non-authoritative meta tag
Fetching https://golang.org/x/image?go-get=1
Parsing meta tags from https://golang.org/x/image?go-get=1 (status code 200)
golang.org/x/image (download)
github.com/aeonurutu/shade/core/gen
github.com/go-gl/gl/v4.1-core/gl
github.com/aeonurutu/shade/core/util/archive
github.com/go-gl/glfw/v3.1/glfw
golang.org/x/image/math/f32
github.com/go-gl/mathgl/mgl32
github.com/aeonurutu/shade/core/time/clock
github.com/aeonurutu/shade/core/time
github.com/aeonurutu/shade/core/util/actor
github.com/aeonurutu/shade/core/shapes
github.com/aeonurutu/shade/core/light
github.com/aeonurutu/shade/core/entity
github.com/aeonurutu/shade/core/shader
github.com/aeonurutu/shade/core/camera
github.com/aeonurutu/shade/core/util/sprite
github.com/aeonurutu/shade/core/splash/ghost
github.com/aeonurutu/shade/core/util/fonts
github.com/aeonurutu/shade/examples/03-collisions/ball
github.com/aeonurutu/shade/examples/03-basic-collisions/ball
github.com/aeonurutu/shade/examples/03-basic-collisions/block
github.com/aeonurutu/shade/examples/03-collisions/block
github.com/aeonurutu/shade/examples/demos/platformer/block
github.com/aeonurutu/shade/core/events
github.com/aeonurutu/shade/core/dev
github.com/aeonurutu/shade/core/display
github.com/aeonurutu/shade/examples/03-basic-collisions/player
github.com/aeonurutu/shade/examples/demos/platformer/player
# github.com/aeonurutu/shade/core/dev
core/dev/dev.go:139: undefined: gen.Version
core/dev/dev.go:140: undefined: gen.GitURL
core/dev/dev.go:140: undefined: gen.Hash
github.com/aeonurutu/shade/examples/demos/pong/player
github.com/aeonurutu/shade/examples/demos/pong/ball
github.com/aeonurutu/shade/core/splash
github.com/aeonurutu/shade/examples/02-animation
github.com/aeonurutu/shade/examples/03-basic-collisions
github.com/aeonurutu/shade/examples/03-collisions
github.com/aeonurutu/shade/examples/04-lighting
github.com/aeonurutu/shade/examples/05-text
github.com/aeonurutu/shade/examples/demos/platformer/game
github.com/aeonurutu/shade/examples/demos/platformer
```

I am assuming that when the PR is merged to master on github.com/aeonurutu/shade, then "go get -u -v github.com/aeonurutu/shade" should start working, correct?  Or is there a flaw in my logic somewhere?
